import { Inter, Sarabun } from 'next/font/google';
import './globals.css';

const saraban = Sarabun({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  variable: '--font-sarabun',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={saraban.className}>{children}</body>
    </html>
  );
}
